Toursim Event Capston Project.
billionsjoel/tour-event-app pull request #1
Opened 2021-12-22 13:01 UTC by billionsjoel

**#This PR does the following: -**

- Personalize the content of my page with a topic that is different from the one in the original design.
- Follows the design guidelines.
- Design the home page.
- Design the about page.
       Each of these pages has versions for 2 different screen sizes:
- Develop Javascript Interactions.
- Design and develop a javascript Dynamic page section.

2021-12-22 21:18 UTC, MrBrN197 requested changes
## Hi, @billionsjoel 👋 

You've done a really nice job so far.
There are some issues that you still need to work on to go to the next project but you are almost there!
## To highlight 👏👏
- ✔Great design

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-22 21:18 UTC, MrBrN197 commented on about-us.html
> +    <section id="main-navigation" class="nav-section">
- [x] Hi, You've implemented the desktop version of the navbar correctly. However, the navbar on the mobile design should have a transparent background as per the design. currently yours has a background of white. please fix this issue for the mobile version.
## Your Design
![image](https://user-images.githubusercontent.com/18730106/147153351-fda2b272-135e-4dfa-ac85-bcab70261ee8.png)

2021-12-22 21:18 UTC, MrBrN197 commented on about-us.html
> +  </section>
- [x] Your footer design is great 👍. please make sure to give this footer section a dark background on the desktop version of the about page. the footer should be dark on the desktop version of the about page. please implement this change 🙏
## Your Design 
![image](https://user-images.githubusercontent.com/18730106/147153750-7c6d4e83-a821-4c43-b7d0-dc94045bc281.png)

## Reference Design
![image](https://user-images.githubusercontent.com/18730106/147153796-0530a298-9217-46a9-a372-607357396148.png)

2021-12-22 21:18 UTC, MrBrN197 commented on index.html
> +            </div>
- [x] Hi please notice in this section that the text is being cut off, so It is not possible to see all the text. please address this issue. ensure that all the text for this page is there and that it is not cut off by the next section.
## Your Design
![image](https://user-images.githubusercontent.com/18730106/147154167-32ff5c35-27fe-45bf-9bdc-73f1b49cd3bb.png)

## Template Design
![image](https://user-images.githubusercontent.com/18730106/147154201-110b51f3-3e63-4027-a2ba-d465e6b46cad.png)

2021-12-22 21:18 UTC, MrBrN197 commented on js/speakers.js
> +for (let i = 0; i <= speakers.length; i += 1) {
- [x] kindly use modern es6 syntax here. you can write `speakers.forEach( (speaker) => { ... })` instead of using a for loop.

2021-12-22 21:18 UTC, MrBrN197 commented on index.html
> +              </div>
- [ ] Hi these cards are designed well, although please make sure you properly align them vertically currently they are not centered in the middle vertically. If you look at the reference they should be.
## Your Design
![image](https://user-images.githubusercontent.com/18730106/147154709-4c05a87c-f6e6-4f15-b0a4-7996467066e0.png)

## Reference Design
![image](https://user-images.githubusercontent.com/18730106/147154766-87f9c51c-2cc6-48c4-99e5-16b1bf5036f4.png)

2021-12-22 21:18 UTC, MrBrN197 commented on about-us.html
> +            </div>
- [ ] Please in this section include the contact information text that is on the reference design. or any other informational text that is after this `.head-text-about` text.
## Reference Design
![image](https://user-images.githubusercontent.com/18730106/147155273-cce1a00e-67ee-446a-bcaa-1ed0ab07fee1.png)

2021-12-22 21:18 UTC, MrBrN197 commented on about-us.html
> +    </section>
- [ ] There is an entire middle section that you are missing here it comes right after this section. it's in the middle of the page before you get to the section with the two images. please add this section to your about page. 
## Reference image (👇 you should have this section of the page)
![image](https://user-images.githubusercontent.com/18730106/147155557-4b101c15-5e1f-4955-8eb3-c38d5fbe37bd.png)

2021-12-22 21:18 UTC, MrBrN197 commented on about-us.html
> +            <h2 class="title-about">Tourism Events Global summit <span class="year"> 2022 </span></h2>
- [ ] To keep inline with correct HTML semantics we should have one `h1` tag on every page. In the about page you don't have a `h1` tag. please implement one.

2021-12-23 04:43 UTC, Cathella approved these changes
## 🟢 Approved 🎉💪🏻

### Hi @billionsjoel 👋🏻, 

Great job done implementing all the changes required by the previous reviewer 💪🏻!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-23 08:58 UTC, merged